<template>
  <div>
    <h1 style="text-align: center"> SyneronBrain </h1>

    <el-row style="margin-top: 20px">
      <el-col :span="3">
        <div class="grid-content"></div>
      </el-col>
      <el-col :span="18">
        <p class="overview_font">
          SneronyBrain is an innovative peptide drug design and discovery platform developed by Syneron. It is a groundbreaking solution that leverages AI-technologies to simplify and enhance the drug discovery process.
        </p>
      </el-col>
      <el-col :span="3">
        <div class="grid-content"></div>
      </el-col>
    </el-row>
    <el-row style="margin-top: 10px">
      <el-col :span="24">
        <div align="center">
          <img src="../../assets/models_img/home-brain.png" style="width:60%;"/>
        </div>
      </el-col>
    </el-row>
    <!-- <span class="demonstration">默认 Hover 指示器触发</span> -->
     
    

    <h2 style="text-align: center"> AutoML </h2>

    <el-row style="margin-top: 20px">
      <el-col :span="3">
        <div class="grid-content"></div>
      </el-col>
      <el-col :span="18">
        <p class="overview_font">
          In the field of peptide drug discovery, we have developed the first-ever automated machine learning (AutoML) platform. This platform includes various modules such as experiment tracing, feature engineering, model deployment, containerization, and AutoML. By utilizing this system, researchers can efficiently implement the model and establish a standardized process in the AI-based dry-wet closed-loop process.
        </p>
        <P class="overview_font">
          The overall architecture of the platform is designed to be robust and scalable, enabling it to support high-throughput virtual screening, AutoML capabilities, and the ability to generate models that align with business goals and objectives.
        </P>
        <P class="overview_font">
          Syn-AutoML is the first AutoML platform created specifically for peptide design. This platform is capable of automating various aspects of model-building, including feature engineering, neural architecture search, hyperparameter tuning, and model compression for deep learning.
        </P>
        <P class="overview_font">
          The feature store is another critical component of the platform, as it allows researchers to store protein/peptide features in either offline or online repositories. This feature store enables researchers to combine features from various sources for training purposes, retrieve fresh feature data for high-throughput virtual screening, and reuse features across different projects and models.
        </P>
        <P class="overview_font">
          The model server component of the platform is designed to host machine-learning models and make their functions available through an API. This feature is crucial for integrating AI into other systems, as it enables other applications to easily incorporate the capabilities of the machine-learning models generated by the platform.
        </P>
        <!-- <p>{{"\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0"}}1. Overall Architecture</p>
        <p>{{"\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0"}}2. AutoML</p>
        <p>{{"\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0"}}3. Feature store</p>
        <p>{{"\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0"}}4. Model Server</p> -->
      </el-col>
      <el-col :span="3">
        <div class="grid-content"></div>
      </el-col>
    </el-row>

    <el-row style="margin-top: 0px">
      <el-col :span="24">
        <div align="center" >
          <el-carousel arrow="always" :interval="30000" height="500px" style="width:60% ; align-items: center;">
          <el-carousel-item class="el-carousel__item" v-for="(img,index) in imgList" :key="index">
            <img v-bind:src="img.url" style="width:100%;height:100%">
          </el-carousel-item>
          </el-carousel>
        </div>
      </el-col>
    </el-row>

    <h2 style="text-align: center"> Pretrained Models </h2>

    <el-row style="margin-top: 20px">
      <el-col :span="3">
        <div class="grid-content"></div>
      </el-col>
      <el-col :span="18">
        <p class="overview_font">
          SneronyBrain features a bunch of pre-trained models that enable the extraction of representations of proteins or peptides, improving downstream task performance.
        </p>
        <p class="overview_font">
          SH-PepBert: This pre-training model is based on the amino acid sequence of peptides, and enables researchers to efficiently extract important representation of peptides for downstream tasks.
        </p>
        <P class="overview_font">
          SH-PepMultiModal: This pre-training model is unique in that it incorporates both structural and sequence information, utilizing contrastive learning to more effectively extract useful information from protein and peptide data.
        </P>
        <p class="overview_font">
          SH-PepGPT: This pre-training model is based on GPT (Generative Pre-trained Transformer) and can be used for end-to-end peptide generation, making it an incredibly valuable tool for researchers working on novel peptide development.
        </p>
        <p class="overview_font">
          By leveraging these pre-trained models, Our algorithm can enhance their ability to accurately predict properties of protein and peptide. The experimental results shows these pre-training models can effectively help with a wide range of downstream tasks.
        </p>
        <!-- <p>{{"\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0"}}1. SH-PepBert: Peptide pre-training model based on amino acid sequence</p>
        <p>{{"\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0"}}2. SH-PepBertS: Peptide pre-training model based on unnatural amino acid sequence</p>
        <p>{{"\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0"}}3. SH-PepMultiModal: Peptide pre-training model based on contrastive learning</p>
        <p>{{"\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0"}}4. SH-PepGPT: GPT based peptide pretrained generator</p> -->
      </el-col>
      <el-col :span="3">
        <div class="grid-content"></div>
      </el-col>
    </el-row>
    <el-row style="margin-top: 0px">
      <el-col :span="24">
        <div align="center" >
          <el-carousel arrow="always" :interval="30000" height="500px" style="width:60% ; align-items: center;">
          <el-carousel-item class="el-carousel__item" v-for="(img,index) in imgList_pretrain" :key="index">
            <img v-bind:src="img.url" style="width:100%;height:100%">
          </el-carousel-item>
          </el-carousel>
        </div>
      </el-col>
    </el-row>
    <h2 style="text-align: center"> High-throughput prediction algorithms </h2>
    <el-row style="margin-top: 20px">
      <el-col :span="3">
        <div class="grid-content"></div>
      </el-col>
      <el-col :span="18">
        <p class="overview_font">
          SneronyBrain has created a collection of powerful high-throughput prediction algorithms that enable researchers to quickly and efficiently navigate the vast chemical space of peptides and identify the most promising candidates. These algorithms include:
        </p>
        <p class="overview_font">
          ST-PepScore: This algorithm is based on peptide sequence and is designed to predict protein-peptide affinity. It is a valuable tool for researchers seeking to optimize peptide selection for a variety of applications.
        </p>
        <P class="overview_font">
          ST-PepInt: Similarly based on peptide sequence, this algorithm focuses on predicting protein-peptide interactions. By accurately predicting these interactions, researchers can gain valuable insights into how peptides might behave in different contexts and identify opportunities for optimization.
        </P>
        <p class="overview_font">
          ST-PepMRS: This algorithm is trained on specific phage display NGS data, and is used for sequence-based affinity prediction. By incorporating this model into their workflows, researchers can more accurately predict peptide performance and make more informed decisions about which candidates to pursue further.
        </p>
        <p class="overview_font">
          Together, these high-throughput prediction algorithms enable researchers to rapidly evaluate large numbers of peptide candidates and identify the most promising options for further investigation. This can greatly accelerate the drug discovery process and lead to more efficient and effective peptide-based therapies.
        </p>
        <!-- <p>{{"\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0"}}1. ST-PepScore: sequence based protein-peptide affinity prediction.</p>
        <p>{{"\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0"}}2. ST-PepInt: sequence based protein-peptide interaction prediction.</p> -->
      </el-col>
      <el-col :span="3">
        <div class="grid-content"></div>
      </el-col>
    </el-row>
    <el-row style="margin-top: 0px">
      <el-col :span="24">
        <div align="center" >
          <el-carousel arrow="always" :interval="30000" height="500px" style="width:60% ; align-items: center;">
          <el-carousel-item class="el-carousel__item" v-for="(img,index) in imgList_high_throughput" :key="index">
            <img v-bind:src="img.url" style="width:100%;height:100%">
          </el-carousel-item>
          </el-carousel>
        </div>
      </el-col>
    </el-row>
    <h2 style="text-align: center"> High-precision prediction algorithms </h2>
    <el-row style="margin-top: 20px">
      <el-col :span="3">
        <div class="grid-content"></div>
      </el-col>
      <el-col :span="18">
        <p class="overview_font">
          In addition to its high-throughput prediction algorithms, SneronyBrain also offers a suite of high-precision forecasting tools that allow researchers to refine and optimize peptide candidates based on structural biology and AlphaFold2. These tools include:
        </p>
        <p class="overview_font">
          ST-PepCarC: ST-PepCarC defines the affinity prediction problem as a competitive matching problem. Because in practical applications, the relative ranking of the affinities of various candidate peptides is more important than the absolute values of their affinities. This can reduce the difficulty of modeling and better tolerate the problem of inaccurate measurement of experimental data. By breaking down AlphaFold-Multimer into deep parts and then incorporating our innovative modules, we have achieved the world's first method for modeling the conformation of cyclic peptides-protein binding.
        </p>
        <p class="overview_font">
          SC-CPPTransformer: This algorithm is based on transformer and pre-trained models, and is used for predicting cell-penetrating peptides (CPPs). The model can be transferred to CPPs containing non-standard amino acids, allowing researchers to explore a wider range of peptides and identify new candidates with enhanced efficacy.   
        </p>
        <p class="overview_font">
          Together, these high-precision forecasting algorithms enable researchers to gain a deeper understanding of how different peptides interact with their targets, and identify the most promising candidates for further development. By combining high-throughput and high-precision approaches, SneronyBrain is revolutionizing the field of peptide drug discovery and accelerating the development of novel candidates.
        </p>
        <!-- <P>{{"\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0"}}1. ST-PepCarC: Cyclopeptide affinity ranking based on Competitive.</P>
        <P>{{"\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0"}}2. SC-CPPTransformer: CPP prediction algorithm based on transformer and pre-trained model which can be transferred to CPP containing non-standard amino acids.</P> -->
      </el-col>
      <el-col :span="3">
        <div class="grid-content"></div>
      </el-col>
    </el-row>
    <el-row style="margin-top: 0px">
      <el-col :span="24">
        <div align="center" >
          <el-carousel arrow="always" :interval="30000" height="500px" style="width:60% ; align-items: center;">
          <el-carousel-item class="el-carousel__item" v-for="(img,index) in imgList_high_precision" :key="index">
            <img v-bind:src="img.url" style="width:100%;height:100%">
          </el-carousel-item>
          </el-carousel>
        </div>
      </el-col>
    </el-row>
    <h2 style="text-align: center"> De novo design </h2>
    <el-row style="margin-top: 20px">
      <el-col :span="3">
        <div class="grid-content"></div>
      </el-col>
      <el-col :span="18">
        <p class="overview_font">
          SneronyBrain offers a variety of de novo peptide generation algorithms, which are useful for De novo design. Additionally, it features a multi-objective optimization framework that leverages reinforcement learning.
        </p>
        <P class="overview_font">
          One of the peptide generators available is SD-PepGPT, which is based on the GPT architecture. This generator is capable of producing novel peptide sequences.
        </P>
        <p class="overview_font">
          Another generator is SD-RL, which is based on reinforcement learning and search algorithms. This generator allows for the efficient generation of peptide sequences that meet various properties in an end-to-end manner. By leveraging this framework, users can generate peptides with desired properties.
        </p>
        <!-- <P>{{"\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0"}}1. SD-PepGPT: GPT based peptide generator</P>
        <P>{{"\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0"}}2. SD-RL: Reinforcement learning framework and search algorithms-based generator to generate peptide sequences that meet various properties in an end-to-end manner efficiently.</P> -->
      </el-col>
      <el-col :span="3">
        <div class="grid-content"></div>
      </el-col>
    </el-row>
    <el-row style="margin-top: 0px">
      <el-col :span="24">
        <div align="center" >
          <el-carousel arrow="always" :interval="30000" height="500px" style="width:60% ; align-items: center;">
          <el-carousel-item class="el-carousel__item" v-for="(img,index) in imgList_de_novo_design" :key="index">
            <img v-bind:src="img.url" style="width:100%;height:100%">
          </el-carousel-item>
          </el-carousel>
        </div>
      </el-col>
    </el-row>
    <h2 style="text-align: center"> Active learning for dry-wet closed-loop. </h2>
    <el-row style="margin-top: 50px">
      <el-col :span="3">
        <div class="grid-content"></div>
      </el-col>
      <el-col :span="18">
        <p class="overview_font">
          Our cutting-edge AI platform is founded upon the active learning framework, a advanced approach that enables us to significantly reduce the number of rounds of dry-wet closed-loop iterations, and minimizes the number of peptides required for synthesis and activity testing. Our revolutionary technology has transformed our research process, increasing its efficiency and expediting the generation of actionable insights. SneronyBrain has already empowered 5+ pipelines to truly realize dry-wet closed-loop.
        </p>
        </el-col>
      <el-col :span="3">
        <div class="grid-content"></div>
      </el-col>
    </el-row>

  </div>
</template>

<script>
import 'element-ui/lib/theme-chalk/index.css'
import ElementUI from 'element-ui'
export default {
  name: 'MainPage',
  data() {
    return {
      mainPage: '',
      imgList:[
        {url:require('@/assets/AutoML/Overall Architecture.png')},
        {url:require('@/assets/AutoML/automljpeg.jpeg')},
        {url:require('@/assets/AutoML/Feature store.png')},
        {url:require('@/assets/AutoML/model_server.png')}
      ],
      imgList_pretrain:[
        {url:require('@/assets/models_img/SH-PepBert.jpeg')},
        {url:require('@/assets/models_img/SH-PepBertS.jpeg')},
        {url:require('@/assets/models_img/SH-PepContrast-or.jpeg')},
        {url:require('@/assets/models_img/SH-GPT.jpeg')}
      ],
      imgList_high_throughput:[
        {url:require('@/assets/models_img/ST-PepScore.png')},
        {url:require('@/assets/models_img/ST-PepInt.png')},
        {url:require('@/assets/models_img/ST-PepMRS-or.jpeg')}      
      ],
      imgList_high_precision:[
        {url:require('@/assets/models_img/ST-PepCarC-or.jpeg')},
        {url:require('@/assets/models_img/SC-CPPTransformer-or.jpeg')}
      ],
      imgList_de_novo_design:[
        {url:require('@/assets/models_img/SH-GPT.jpeg')},
        {url:require('@/assets/models_img/SD-RL.jpeg')}
      ]
    }
  },
  methods: {
    k8sClick() {
      window.location.href = 'https://81.70.177.174:30443/'
    },
    rayClick() {
      window.location.href = 'http://81.70.177.174:5058/'
    }
  }
}

</script>

<style scoped>

.main_img {
  width: 80%;
}

.grid-content {
  border-radius: 4px;
  min-height: 36px;
}


.overview_font {
  font-size: 20px;
  font-family: "Microsoft YaHei","Times New Roman", Times, serif;
  text-align: justify;
  font-weight: normal;
  line-height: 1.5;
}

.el-carousel__item h3 {
    color: #475669;
    font-size: 14px;
    opacity: 0.75;
    line-height: 150px;
    margin: 0;
  }

  .el-carousel__item:nth-child(2n) {
     background-color: #99a9bf;
  }
  
  .el-carousel__item:nth-child(2n+1) {
     background-color: #d3dce6;
  }

  .carousel-img {
    max-width: 100%;
    max-height: 100%;
  }

  
  .el-carousel__item {
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
}
</style>
